/**
 * Permission definitions and bootstrap role map
 * Mirrors backend PHP config for frontend RBAC
 * When API does not return user.permissions, we derive from role via BOOTSTRAP_ROLE_MAP
 */

/** Permission keys for route meta and RBAC - use these instead of string literals */
export const PERMISSIONS = {
  NOTIFICATIONS_VIEW: 'notifications.view',
  CONTRACTS_VIEW: 'contracts.view',
  HR_USERS_CREATE: 'hr.users.create',
  HR_DASHBOARD_VIEW: 'hr.dashboard.view',
  HR_TEAMS_MANAGE: 'hr.teams.manage',
  HR_PERFORMANCE_VIEW: 'hr.performance.view',
  HR_REPORTS_VIEW: 'hr.reports.view',
  AGENTS_MANAGE: 'agents.manage',
  MARKETING_DASHBOARD_VIEW: 'marketing.dashboard.view',
  MARKETING_PROJECTS_VIEW: 'marketing.projects.view',
  MARKETING_TASKS_VIEW: 'marketing.tasks.view',
  MARKETING_TEAMS_VIEW: 'marketing.teams.view',
  MARKETING_REPORTS_VIEW: 'marketing.reports.view',
  MARKETING_PLANS_CREATE: 'marketing.plans.create',
  USE_AI_ASSISTANT: 'use-ai-assistant',
  MANAGE_AI_KNOWLEDGE: 'manage-ai-knowledge',
  SALES_DASHBOARD_VIEW: 'sales.dashboard.view',
  SALES_TARGETS_VIEW: 'sales.targets.view',
  SALES_PROJECTS_VIEW: 'sales.projects.view',
  SALES_RESERVATIONS_VIEW: 'sales.reservations.view',
  SALES_ATTENDANCE_VIEW: 'sales.attendance.view',
  SALES_NEGOTIATION_APPROVE: 'sales.negotiation.approve',
  SALES_TEAM_MANAGE: 'sales.team.manage',
  SALES_TASKS_MANAGE: 'sales.tasks.manage',
  SALES_WAITING_LIST_CREATE: 'sales.waiting_list.create',
  SALES_PROJECTS_ALLOCATE_SHIFTS: 'sales.projects.allocate_shifts',
  SALES_PAYMENT_PLAN_MANAGE: 'sales.payment-plan.manage',
  CREDIT_DASHBOARD_VIEW: 'credit.dashboard.view',
  CREDIT_BOOKINGS_VIEW: 'credit.bookings.view',
  CREDIT_FINANCING_MANAGE: 'credit.financing.manage',
  CREDIT_TITLE_TRANSFER_MANAGE: 'credit.title_transfer.manage',
  CREDIT_CLAIM_FILES_GENERATE: 'credit.claim_files.generate',
  ACCOUNTING_DASHBOARD_VIEW: 'accounting.dashboard.view',
  ACCOUNTING_NOTIFICATIONS_VIEW: 'accounting.notifications.view',
  ACCOUNTING_SOLD_UNITS_VIEW: 'accounting.sold-units.view',
  ACCOUNTING_COMMISSIONS_APPROVE: 'accounting.commissions.approve',
  ACCOUNTING_DEPOSITS_VIEW: 'accounting.deposits.view',
  ACCOUNTING_SALARIES_VIEW: 'accounting.salaries.view',
  ACCOUNTING_DOWN_PAYMENT_CONFIRM: 'accounting.down_payment.confirm',
};

export const PERMISSION_DEFINITIONS = {
  'contracts.view': 'View contract lists and details.',
  'contracts.view_all': 'View all contracts across users.',
  'contracts.create': 'Create new contracts.',
  'contracts.approve': 'Approve or reject contracts.',
  'contracts.delete': 'Delete contracts.',
  'units.view': 'View contract units.',
  'units.edit': 'Create or update contract units.',
  'units.csv_upload': 'Upload CSV files for units.',
  'second_party.view': 'View second party data.',
  'second_party.edit': 'Edit second party data.',
  'departments.boards.view': 'View boards department data.',
  'departments.boards.edit': 'Edit boards department data.',
  'departments.photography.view': 'View photography department data.',
  'departments.photography.edit': 'Edit photography department data.',
  'departments.montage.view': 'View montage department data.',
  'departments.montage.edit': 'Edit montage department data.',
  'dashboard.analytics.view': 'View dashboard analytics.',
  'notifications.view': 'View notifications.',
  'notifications.manage': 'Manage and send notifications.',
  'employees.manage': 'Manage employees.',
  'projects.view': 'View projects and units.',
  'projects.create': 'Create and enter project data.',
  'projects.media.upload': 'Upload images and videos.',
  'projects.media.approve': 'Approve images and videos (Manager only).',
  'projects.team.create': 'Create project team.',
  'projects.team.assign_leader': 'Assign team leader.',
  'projects.team.allocate': 'Allocate team to project.',
  'projects.approve': 'Approve projects (Manager only).',
  'projects.archive': 'Archive projects (Manager only).',
  'sales.dashboard.view': 'View sales dashboard.',
  'sales.projects.view': 'View sales projects.',
  'sales.units.view': 'View project units.',
  'sales.units.book': 'Book available units.',
  'sales.reservations.create': 'Create reservations.',
  'sales.reservations.view': 'View reservations.',
  'sales.reservations.confirm': 'Confirm reservations.',
  'sales.reservations.cancel': 'Cancel reservations.',
  'sales.waiting_list.create': 'Create waiting list booking.',
  'sales.waiting_list.convert': 'Convert waiting to confirmed (Leader only).',
  'sales.goals.view': 'View assigned goals.',
  'sales.goals.create': 'Create goals for team (Leader only).',
  'sales.schedule.view': 'View work schedule.',
  'sales.targets.view': 'View targets.',
  'sales.targets.update': 'Update target status.',
  'sales.team.manage': 'Manage team (leader only).',
  'sales.attendance.view': 'View attendance.',
  'sales.attendance.manage': 'Manage team attendance.',
  'sales.tasks.manage': 'Manage marketing tasks.',
  'sales.tasks.create_for_marketing': 'Create daily tasks for marketing.',
  'sales.projects.allocate_shifts': 'Allocate projects/shifts to marketing staff.',
  'sales.negotiation.approve': 'Approve or reject negotiation requests.',
  'sales.payment-plan.manage': 'Create and manage off-plan payment plans.',
  'editing.projects.view': 'View projects and units.',
  'editing.media.upload': 'Upload edited images and videos.',
  'hr.dashboard.view': 'View HR dashboard KPIs.',
  'hr.teams.manage': 'Manage teams (CRUD and member assignment).',
  'hr.employees.manage': 'Full employee management.',
  'hr.users.create': 'Create new users with roles.',
  'hr.performance.view': 'View team and employee performance.',
  'hr.warnings.manage': 'Issue and view employee warnings.',
  'hr.contracts.manage': 'Create and download employee contracts.',
  'hr.reports.view': 'Access HR reports.',
  'hr.reports.print': 'Print performance reports.',
  'marketing.dashboard.view': 'View marketing dashboard KPIs.',
  'marketing.projects.view': 'View marketing projects and plans.',
  'marketing.plans.create': 'Create marketing plans.',
  'marketing.budgets.manage': 'Manage budgets and forecasts.',
  'marketing.tasks.view': 'View marketing tasks and achievement rates.',
  'marketing.tasks.confirm': 'Confirm daily task execution.',
  'marketing.reports.view': 'View performance and budget reports.',
  'marketing.teams.view': 'View marketing teams.',
  'marketing.teams.manage': 'Manage marketing teams and assign campaigns.',
  'exclusive_projects.view': 'View exclusive project requests.',
  'exclusive_projects.request': 'Request exclusive project (all except HR).',
  'exclusive_projects.approve': 'Approve exclusive project requests (PM Manager only).',
  'exclusive_projects.contract.complete': 'Complete contract after approval.',
  'exclusive_projects.contract.export': 'Export contract copy.',
  'use-ai-assistant': 'Access the in-app AI help assistant.',
  'manage-ai-knowledge': 'Manage AI assistant knowledge base entries.',
  'credit.dashboard.view': 'View Credit department dashboard KPIs.',
  'credit.bookings.view': 'View bookings in Credit department.',
  'credit.financing.manage': 'Manage bank financing tracker stages.',
  'credit.title_transfer.manage': 'Manage title transfer process.',
  'credit.claim_files.generate': 'Generate claim files.',
  'accounting.dashboard.view': 'View accounting dashboard metrics.',
  'accounting.notifications.view': 'View accounting notifications.',
  'accounting.sold-units.view': 'View sold units with commission information.',
  'accounting.sold-units.manage': 'Manage sold units and commissions.',
  'accounting.commissions.approve': 'Approve or reject commission distributions.',
  'accounting.commissions.create': 'Create manual commissions.',
  'accounting.deposits.view': 'View deposit information.',
  'accounting.deposits.manage': 'Manage deposits (confirm, refund).',
  'accounting.salaries.view': 'View employee salaries and commissions.',
  'accounting.salaries.distribute': 'Create and manage salary distributions.',
  'accounting.down_payment.confirm': 'Confirm down payments.',
  'agents.manage': 'Manage AI/Chatbot agents (create, edit, delete).',
};

/**
 * Bootstrap role map - for migration/seeding and frontend fallback
 * When API does NOT return user.permissions, we derive permissions from user.type + user.is_leader / user.is_manager
 * Keys: backend role strings. sales_leader = sales role (type 5) + is_manager=true or is_leader=true
 */
export const BOOTSTRAP_ROLE_MAP = {
  admin: [
    'contracts.view',
    'contracts.view_all',
    'contracts.create',
    'contracts.approve',
    'contracts.delete',
    'units.view',
    'units.edit',
    'units.csv_upload',
    'second_party.view',
    'second_party.edit',
    'departments.boards.view',
    'departments.boards.edit',
    'departments.photography.view',
    'departments.photography.edit',
    'departments.montage.view',
    'departments.montage.edit',
    'dashboard.analytics.view',
    'notifications.view',
    'notifications.manage',
    'employees.manage',
    'projects.view',
    'projects.create',
    'projects.media.upload',
    'projects.media.approve',
    'projects.team.create',
    'projects.team.assign_leader',
    'projects.team.allocate',
    'projects.approve',
    'projects.archive',
    'sales.dashboard.view',
    'sales.projects.view',
    'sales.units.view',
    'sales.units.book',
    'sales.reservations.create',
    'sales.reservations.view',
    'sales.reservations.confirm',
    'sales.reservations.cancel',
    'sales.waiting_list.create',
    'sales.waiting_list.convert',
    'sales.goals.view',
    'sales.goals.create',
    'sales.schedule.view',
    'sales.targets.view',
    'sales.targets.update',
    'sales.team.manage',
    'sales.attendance.view',
    'sales.attendance.manage',
    'sales.tasks.manage',
    'sales.tasks.create_for_marketing',
    'sales.projects.allocate_shifts',
    'sales.negotiation.approve',
    'sales.payment-plan.manage',
    'editing.projects.view',
    'editing.media.upload',
    'hr.dashboard.view',
    'hr.teams.manage',
    'hr.employees.manage',
    'hr.users.create',
    'hr.performance.view',
    'hr.warnings.manage',
    'hr.contracts.manage',
    'hr.reports.view',
    'hr.reports.print',
    'marketing.dashboard.view',
    'marketing.projects.view',
    'marketing.plans.create',
    'marketing.budgets.manage',
    'marketing.tasks.view',
    'marketing.tasks.confirm',
    'marketing.reports.view',
    'marketing.teams.view',
    'marketing.teams.manage',
    'exclusive_projects.view',
    'exclusive_projects.request',
    'exclusive_projects.approve',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'credit.dashboard.view',
    'credit.bookings.view',
    'credit.financing.manage',
    'credit.title_transfer.manage',
    'credit.claim_files.generate',
    'accounting.dashboard.view',
    'accounting.notifications.view',
    'accounting.sold-units.view',
    'accounting.sold-units.manage',
    'accounting.commissions.approve',
    'accounting.commissions.create',
    'accounting.deposits.view',
    'accounting.deposits.manage',
    'accounting.salaries.view',
    'accounting.salaries.distribute',
    'accounting.down_payment.confirm',
    'use-ai-assistant',
    'manage-ai-knowledge',
    'agents.manage',
  ],
  project_management: [
    'contracts.view',
    'contracts.view_all',
    'contracts.approve',
    'units.view',
    'units.edit',
    'units.csv_upload',
    'second_party.view',
    'second_party.edit',
    'departments.boards.view',
    'departments.boards.edit',
    'departments.photography.view',
    'departments.photography.edit',
    'dashboard.analytics.view',
    'notifications.view',
    'projects.view',
    'projects.create',
    'projects.media.upload',
    'projects.team.create',
    'projects.team.assign_leader',
    'projects.team.allocate',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  project_acquisition: [
    'contracts.view',
    'contracts.create',
    'contracts.view_all',
    'notifications.view',
    'projects.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  editor: [
    'contracts.view',
    'contracts.view_all',
    'departments.montage.view',
    'departments.montage.edit',
    'notifications.view',
    'editing.projects.view',
    'editing.media.upload',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  developer: [
    'contracts.view',
    'contracts.create',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  marketing: [
    'marketing.dashboard.view',
    'marketing.projects.view',
    'marketing.plans.create',
    'marketing.budgets.manage',
    'marketing.tasks.view',
    'marketing.tasks.confirm',
    'marketing.reports.view',
    'marketing.teams.view',
    'marketing.teams.manage',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  sales: [
    'sales.dashboard.view',
    'sales.projects.view',
    'sales.units.view',
    'sales.units.book',
    'sales.reservations.create',
    'sales.reservations.view',
    'sales.reservations.confirm',
    'sales.reservations.cancel',
    'sales.waiting_list.create',
    'sales.goals.view',
    'sales.schedule.view',
    'sales.targets.view',
    'sales.targets.update',
    'sales.attendance.view',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  sales_leader: [
    'sales.dashboard.view',
    'sales.projects.view',
    'sales.units.view',
    'sales.units.book',
    'sales.reservations.create',
    'sales.reservations.view',
    'sales.reservations.confirm',
    'sales.reservations.cancel',
    'sales.waiting_list.create',
    'sales.waiting_list.convert',
    'sales.goals.view',
    'sales.goals.create',
    'sales.schedule.view',
    'sales.targets.view',
    'sales.targets.update',
    'sales.team.manage',
    'sales.attendance.view',
    'sales.attendance.manage',
    'sales.tasks.manage',
    'sales.tasks.create_for_marketing',
    'sales.projects.allocate_shifts',
    'sales.negotiation.approve',
    'sales.payment-plan.manage',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  hr: [
    'hr.dashboard.view',
    'hr.teams.manage',
    'hr.employees.manage',
    'hr.users.create',
    'hr.performance.view',
    'hr.warnings.manage',
    'hr.contracts.manage',
    'hr.reports.view',
    'hr.reports.print',
    'notifications.view',
    'exclusive_projects.request',
    'use-ai-assistant',
  ],
  credit: [
    'credit.dashboard.view',
    'credit.bookings.view',
    'credit.financing.manage',
    'credit.title_transfer.manage',
    'credit.claim_files.generate',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  accounting: [
    'accounting.dashboard.view',
    'accounting.notifications.view',
    'accounting.sold-units.view',
    'accounting.sold-units.manage',
    'accounting.commissions.approve',
    'accounting.commissions.create',
    'accounting.deposits.view',
    'accounting.deposits.manage',
    'accounting.salaries.view',
    'accounting.salaries.distribute',
    'accounting.down_payment.confirm',
    'notifications.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
  ],
  inventory: [
    'contracts.view',
    'contracts.view_all',
    'units.view',
    'second_party.view',
    'notifications.view',
    'use-ai-assistant',
  ],
  default: [
    'contracts.view',
    'notifications.view',
    'exclusive_projects.request',
    'use-ai-assistant',
  ],
};

/**
 * Map frontend role type (number) to bootstrap role key
 * sales_leader: role 5 + (is_manager or is_leader) => use sales_leader map
 */
export const ROLE_TO_BOOTSTRAP_KEY = {
  0: 'marketing',
  1: 'admin',
  2: 'project_acquisition',
  3: 'project_management',
  4: 'editor',
  5: 'sales',
  6: 'credit',
  7: 'accounting',
  8: 'hr',
  9: 'hr',
};
