export const PERMISSION_DEFINITIONS = {
  'contracts.view': 'View contract lists and details.',
  'contracts.view_all': 'View all contracts across users.',
  'contracts.create': 'Create new contracts.',
  'contracts.approve': 'Approve or reject contracts.',
  'contracts.delete': 'Delete contracts.',
  'units.view': 'View contract units.',
  'units.edit': 'Create or update contract units.',
  'units.csv_upload': 'Upload CSV files for units.',
  'second_party.view': 'View second party data.',
  'second_party.edit': 'Edit second party data.',
  'departments.boards.view': 'View boards department data.',
  'departments.boards.edit': 'Edit boards department data.',
  'departments.photography.view': 'View photography department data.',
  'departments.photography.edit': 'Edit photography department data.',
  'departments.montage.view': 'View montage department data.',
  'departments.montage.edit': 'Edit montage department data.',
  'dashboard.analytics.view': 'View dashboard analytics.',
  'notifications.view': 'View notifications.',
  'notifications.manage': 'Manage and send notifications.',
  'employees.manage': 'Manage employees.',
  'projects.view': 'View projects and units.',
  'projects.create': 'Create and enter project data.',
  'projects.media.upload': 'Upload images and videos.',
  'projects.media.approve': 'Approve images and videos (Manager only).',
  'projects.team.create': 'Create project team.',
  'projects.team.assign_leader': 'Assign team leader.',
  'projects.team.allocate': 'Allocate team to project.',
  'projects.approve': 'Approve projects (Manager only).',
  'projects.archive': 'Archive projects (Manager only).',
  'sales.dashboard.view': 'View sales dashboard.',
  'sales.projects.view': 'View sales projects.',
  'sales.units.view': 'View project units.',
  'sales.units.book': 'Book available units.',
  'sales.reservations.create': 'Create reservations.',
  'sales.reservations.view': 'View reservations.',
  'sales.reservations.confirm': 'Confirm reservations.',
  'sales.reservations.cancel': 'Cancel reservations.',
  'sales.waiting_list.create': 'Create waiting list booking.',
  'sales.waiting_list.convert': 'Convert waiting to confirmed (Leader only).',
  'sales.goals.view': 'View assigned goals.',
  'sales.goals.create': 'Create goals for team (Leader only).',
  'sales.schedule.view': 'View work schedule.',
  'sales.targets.view': 'View targets.',
  'sales.targets.update': 'Update target status.',
  'sales.team.manage': 'Manage team (leader only).',
  'sales.attendance.view': 'View attendance.',
  'sales.attendance.manage': 'Manage team attendance.',
  'sales.tasks.manage': 'Manage marketing tasks.',
  'sales.tasks.create_for_marketing': 'Create daily tasks for marketing.',
  'sales.projects.allocate_shifts': 'Allocate projects/shifts to marketing staff.',
  'sales.negotiation.approve': 'Approve or reject negotiation requests.',
  'sales.payment_plan.manage': 'Create and manage off-plan payment plans.',
  'sales.sold_units.view': 'View sold units list and commission summaries.',
  'sales.search_alerts.view': 'Manage unit search alerts (طلب وحدات) for clients.',
  'sales.deposits.view': 'View deposit management and follow-up data.',
  'sales.analytics.view': 'View sales analytics dashboard and commission reports.',
  'tasks.create':
    'Create and manage tasks (إدارة المهام - إضافة مهمة، مهامي). System-wide: POST /api/tasks, GET /api/my-tasks, PATCH /api/my-tasks/{id}/status.',
  'ai-calls.manage': 'Manage AI calling system: initiate, view, retry calls and manage scripts.',
  'editing.projects.view': 'View projects and units.',
  'editing.media.upload': 'Upload edited images and videos.',
  'hr.dashboard.view': 'View HR dashboard KPIs.',
  'hr.teams.manage': 'Manage teams (CRUD and member assignment).',
  'hr.employees.manage': 'Full employee management.',
  'hr.users.create': 'Create new users with roles.',
  'hr.users.view': 'View employees list (for plans and team selection).',
  'hr.performance.view': 'View team and employee performance.',
  'hr.warnings.manage': 'Issue and view employee warnings.',
  'hr.contracts.manage': 'Create and download employee contracts.',
  'hr.reports.view': 'Access HR reports.',
  'hr.reports.print': 'Print performance reports.',
  'marketing.dashboard.view': 'View marketing dashboard KPIs.',
  'marketing.projects.view': 'View marketing projects and plans.',
  'marketing.plans.create': 'Create marketing plans.',
  'marketing.budgets.manage': 'Manage budgets and forecasts.',
  'marketing.tasks.view': 'View marketing tasks and achievement rates.',
  'marketing.tasks.confirm': 'Confirm daily task execution.',
  'marketing.reports.view': 'View performance and budget reports.',
  'marketing.teams.view': 'View marketing teams.',
  'marketing.teams.manage': 'Manage marketing teams and assign campaigns.',
  'exclusive_projects.view': 'View exclusive project requests.',
  'exclusive_projects.request': 'Request exclusive project (all except HR).',
  'exclusive_projects.approve': 'Approve exclusive project requests (PM Manager only).',
  'exclusive_projects.contract.complete': 'Complete contract after approval.',
  'exclusive_projects.contract.export': 'Export contract copy.',
  'use-ai-assistant': 'Access the in-app AI help assistant.',
  'manage-ai-knowledge': 'Manage AI assistant knowledge base entries.',
  'credit.dashboard.view': 'View Credit department dashboard KPIs.',
  'credit.bookings.view': 'View bookings in Credit department.',
  'credit.financing.manage': 'Manage bank financing tracker stages.',
  'credit.title_transfer.manage': 'Manage title transfer process.',
  'credit.claim_files.generate': 'Generate claim files.',
  'credit.claim_files.view': 'View claim files in Credit department.',
  'credit.claim_files.manage': 'Manage claim files (create, combined, bulk) in Credit department.',
  'accounting.dashboard.view': 'View accounting dashboard metrics.',
  'accounting.notifications.view': 'View accounting notifications.',
  'accounting.sold-units.view': 'View sold units with commission information.',
  'accounting.sold-units.manage': 'Manage sold units and commissions.',
  'accounting.commissions.approve': 'Approve or reject commission distributions.',
  'accounting.commissions.create': 'Create manual commissions.',
  'accounting.deposits.view': 'View deposit information.',
  'accounting.deposits.manage': 'Manage deposits (confirm, refund).',
  'accounting.salaries.view': 'View employee salaries and commissions.',
  'accounting.salaries.distribute': 'Create and manage salary distributions.',
  'accounting.down_payment.confirm': 'Confirm down payments.',
  'agents.manage': 'Manage AI/Chatbot agents (create, edit, delete).',
  'developers.list.view': 'View developers list (e.g. in exclusive project request or accounting).',
};
