export * from './hrPdfBlob.js';
export * from './hrDashboardEmployees.js';
export * from './hrPerformance.js';
export * from './hrReportingGenerate.js';
export * from './hrTeams.js';
export * from './hrOperations.js';

import {
  getDashboardMetrics,
  getEmployees,
  getEmployeeById,
  createEmployee,
  updateEmployee,
  deleteEmployee,
} from './hrDashboardEmployees.js';
import { getMarketerPerformance, setMarketerGoal } from './hrPerformance.js';
import {
  generateTeamPerformanceReport,
  generateMarketerReport,
  generateEmployeesReport,
  generateExpiringContractsReport,
} from './hrReportingGenerate.js';
import {
  getTeams,
  getHRTeamMembers,
  getTeamById,
  createTeam,
  updateTeam,
  deleteTeam,
  linkMarketersToTeam,
  getTeamContracts,
  getTeamContractLocations,
  getTeamsForContract,
  getTeamSalesAverage,
} from './hrTeams.js';
import {
  refreshDashboard,
  createHRTeam,
  updateHRTeam,
  deleteHRTeam,
  assignTeamMember,
  removeTeamMember,
  listMarketerPerformance,
  showMarketerPerformance,
  listUsers,
  createUser,
  showUser,
  updateUser,
  toggleUserStatus,
  deleteUser,
  uploadUserFiles,
  getUserWarnings,
  listUserWarnings,
  createWarning,
  deleteWarning,
  getUserContracts,
  listUserContracts,
  createUserContract,
  showHRContract,
  updateHRContract,
  generateContractPDF,
  downloadContractPDF,
  activateContract,
  terminateContract,
  getTeamPerformanceReport,
  getMarketerPerformanceReport,
  getEmployeeCountReport,
  getExpiringContractsReport,
} from './hrOperations.js';

const hrService = {
  getDashboardMetrics,
  refreshDashboard,
  getEmployees,
  getEmployeeById,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getTeams,
  getHRTeamMembers,
  getTeamById,
  createTeam,
  updateTeam,
  deleteTeam,
  linkMarketersToTeam,
  getTeamContracts,
  getTeamContractLocations,
  getTeamsForContract,
  getTeamSalesAverage,
  createHRTeam,
  updateHRTeam,
  deleteHRTeam,
  assignTeamMember,
  removeTeamMember,
  getMarketerPerformance,
  setMarketerGoal,
  listMarketerPerformance,
  showMarketerPerformance,
  listUsers,
  createUser,
  showUser,
  updateUser,
  toggleUserStatus,
  deleteUser,
  uploadUserFiles,
  getUserWarnings,
  listUserWarnings,
  createWarning,
  deleteWarning,
  getUserContracts,
  listUserContracts,
  createUserContract,
  showHRContract,
  updateHRContract,
  generateContractPDF,
  downloadContractPDF,
  activateContract,
  terminateContract,
  generateTeamPerformanceReport,
  generateMarketerReport,
  generateEmployeesReport,
  generateExpiringContractsReport,
  getTeamPerformanceReport,
  getMarketerPerformanceReport,
  getEmployeeCountReport,
  getExpiringContractsReport,
};

export default hrService;
